package artifacts

const (
	ArtifactName     = "ARTIFACT_NAME"
	ArtifactUrl      = "ARTIFACT_URL"
	ArtifactVersion  = "ARTIFACT_VERSION"
	ArtifactType     = "ARTIFACT_TYPE"
	ArtifactDigest   = "ARTIFACT_DIGEST"
	ArtifactLabel    = "ARTIFACT_LABEL"
	GithubRunId      = "GITHUB_RUN_ID"
	GithubRunAttempt = "GITHUB_RUN_ATTEMPT"
	GithubRunNumber  = "GITHUB_RUN_NUMBER"

	CloudbeesApiUrl            = "CLOUDBEES_API_URL"
	PUBLISHED                  = "PUBLISHED"
	GithubRepository           = "GITHUB_REPOSITORY"
	GithubWorkflowRef          = "GITHUB_WORKFLOW_REF"
	GithubServerUrl            = "GITHUB_SERVER_URL"
	BuildArtifactType          = "cloudbees.platform.register.build.artifact"
	SpecVersion                = "1.0"
	ContentTypeJson            = "application/json"
	ContentTypeHeaderKey       = "Content-Type"
	ContentTypeCloudEventsJson = "application/cloudevents+json"
	AuthorizationHeaderKey     = "Authorization"
	Bearer                     = "Bearer "
	PostMethod                 = "POST"
	GithubProvider             = "GITHUB"
	GithubJobName              = "GITHUB_JOB"
	ActionIdTokenRequestUrl    = "ACTIONS_ID_TOKEN_REQUEST_URL"
	ActionIdTokenRequestToken  = "ACTIONS_ID_TOKEN_REQUEST_TOKEN"
	AccessToken                = "accessToken"
)
