name: Test OIDC Token

on:
  workflow_dispatch:  

jobs:
  print-oidc-token:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  
      contents: read   

    steps:
      - name: Request OIDC Token
        id: get_token
        run: |
          echo "Requesting OIDC token..."
          RESPONSE=$(curl -sSL -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL")
          TOKEN=$(echo "$RESPONSE" | jq -r .value)
          echo "OIDC token retrieved. Length: ${#TOKEN}"
          echo "$TOKEN" > oidc_token.txt
          head -c 300 oidc_token.txt
