name: Test OIDC Token

on:
  workflow_dispatch:  

jobs:
  print-oidc-token:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  
      contents: read   

    steps:
      - name: Request OIDC Token
        id: get_token
        run: |
          echo "Requesting OIDC token..."
          TOKEN=$(curl -sSL -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL")
          echo "::add-mask::$TOKEN"
          echo "OIDC token retrieved. Length: ${#TOKEN}"
          echo "$TOKEN" > oidc_token.txt
          head -c 200 oidc_token.txt  # print first 200 chars for verification
