name: Test LOCAL OIDC

on:
  workflow_dispatch:
  
jobs:
  run-go-action:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run My Custom Go Action
        uses: HemalaDev57/TestAction@master
        with:
          name: "custom-action"
          version: 1.0.1
          url: "ghcr.io/hemaladev57/testaction/custom-action:latest"
          digest: "test"
          type: "docker"
          cloudbees-url: "https://e4e7-2401-4900-6341-13ac-508e-809-7d9e-bb42.ngrok-free.app"
